import esbuild from "esbuild";
import process from "process";
import {builtinModules} from "node:module";
import {readFileSync, writeFileSync} from "node:fs";
import {dirname, join} from "node:path";
import {fileURLToPath} from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

function writeStylesCss() {
	const leafletCss = readFileSync(
		join(__dirname, "node_modules/leaflet/dist/leaflet.css"),
		"utf8",
	);
	const trackCss = readFileSync(
		join(__dirname, "src/styles/track-view.css"),
		"utf8",
	);
	writeFileSync(
		join(__dirname, "styles.css"),
		`${leafletCss}\n${trackCss}`,
		"utf8",
	);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [
		{
			name: "trackdex-assets",
			setup(build) {
				build.onEnd((result) => {
					if (result.errors.length > 0) {
						return;
					}
					writeStylesCss();
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
