/** Single timed operation record (`perf_runs`, §14.2). */
export interface PerfRunRecord {
	readonly runId: string;
	readonly operation: string;
	readonly startedAtUtc: string;
	readonly endedAtUtc: string;
	readonly durationMs: number;
	readonly itemsCount: number;
	readonly success: boolean;
	readonly context?: Record<string, string | number | boolean | null>;
}

export type PerfCounterName =
	| "files_scanned"
	| "files_parsed"
	| "parse_errors"
	| "places_reindexed"
	| "links_updated";

/**
 * Lightweight performance instrumentation for milestone 0.10 perf-report.
 */
export interface PerfMetricsPort {
	recordRun(record: PerfRunRecord): void;
	incrementCounter(name: PerfCounterName, delta?: number): void;
	/**
	 * Returns a function that records duration when invoked (e.g. batch timing).
	 * `runId` may be supplied by the caller or generated by the adapter.
	 */
	startTimer(
		operation: string,
		context?: PerfRunRecord["context"],
	): (outcome: { success: boolean; itemsCount?: number; runId?: string }) => void;
}
