import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
TODO: set repository URL in this banner
*/
`;

const prod = (process.argv[2] === "production");

const SQL_WASM_PATH = join(ROOT, "node_modules/sql.js/dist/sql-wasm.wasm");

/** Inline sql.js WASM for Obsidian (no separate .wasm asset in plugin folder). */
function sqlWasmEmbedPlugin() {
	return {
		name: "sql-wasm-embed",
		setup(build) {
			build.onResolve({ filter: /^trackdex:sql-wasm$/ }, () => ({
				path: "trackdex-sql-wasm",
				namespace: "sql-wasm-embed",
			}));
			build.onLoad({ filter: /.*/, namespace: "sql-wasm-embed" }, () => {
				const wasm = readFileSync(SQL_WASM_PATH);
				const base64 = wasm.toString("base64");
				return {
					contents: [
						`const SQL_WASM_BASE64 = ${JSON.stringify(base64)};`,
						"export function getSqlWasmBinary() {",
						"  if (typeof Buffer !== 'undefined') {",
						"    return new Uint8Array(Buffer.from(SQL_WASM_BASE64, 'base64'));",
						"  }",
						"  const bin = atob(SQL_WASM_BASE64);",
						"  const bytes = new Uint8Array(bin.length);",
						"  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);",
						"  return bytes;",
						"}",
					].join("\n"),
					loader: "js",
				};
			});
		},
	};
}

/** Production builds replace spike command modules with no-op stubs (esbuild always bundles import()). */
function stripSpikeCommandModulesPlugin() {
	const spikeCommandStub = [
		"export function registerStorageSpikeCommand() {}",
		"export function registerFitParserSpikeCommand() {}",
	].join("\n");
	return {
		name: "trackdex-strip-spike-commands",
		setup(build) {
			build.onResolve(
				{ filter: /register-(storage|fit-parser)-spike-command/ },
				() => ({
					path: "trackdex-spike-stub",
					namespace: "trackdex-spike-stub",
				}),
			);
			build.onLoad(
				{ filter: /.*/, namespace: "trackdex-spike-stub" },
				() => ({
					contents: spikeCommandStub,
					loader: "js",
				}),
			);
		},
	};
}

function writeStylesCss() {
	const leafletCss = readFileSync(
		join(ROOT, "node_modules/leaflet/dist/leaflet.css"),
		"utf8",
	);
	const trackCss = readFileSync(
		join(ROOT, "src/styles/track-view.css"),
		"utf8",
	);
	writeFileSync(
		join(ROOT, "styles.css"),
		`${leafletCss}\n${trackCss}`,
		"utf8",
	);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: [join(ROOT, "src/main.ts")],
	tsconfig: join(ROOT, "tsconfig.json"),
	alias: {
		domain: join(ROOT, "src/domain"),
		application: join(ROOT, "src/application"),
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: join(ROOT, "main.js"),
	minify: prod,
	plugins: [
		sqlWasmEmbedPlugin(),
		...(prod ? [stripSpikeCommandModulesPlugin()] : []),
		{
			name: "trackdex-assets",
			setup(build) {
				build.onEnd((result) => {
					if (result.errors.length > 0) {
						return;
					}
					writeStylesCss();
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
